In [2]:
#Features
# SIMD vector processing
# effective cache system
# MATLAB Replacement
# Useful in ML
# Load Numpy

In [150]:
import numpy as np

# BASICS  (Creating Arrays, Shape, Size etc.)

In [68]:
#BASICS  (Creating Arrays, Shape, Size etc.)

# 1_D
a = np.array([2,3,5])
a

# 2_D
b = np.array([[2,5,6],[5,8,9]], dtype = 'int16')
b
v = b.size

#Get The dimention
a.ndim

#Get Shape
print(b.shape)

#Get Data_Type
a.dtype

#Get Size
print(b.size)

#Get Item_Size
a.itemsize

#Get Total Size
# = a.itemsize * a.size
a.nbytes

(2, 3)
6


12

# Accessing/changing specific elements rows, cloumns etc

In [248]:
#Accessing/changing specific elements rows, cloumns etc

a = np.array([[2,5,6,5,8,9],[5,8,9,11,63,59]])
print(a)
x = a[:,3]
print(x)
print(a[1,4])
print(a[1,:])

#Get Specific elemets with changes on runtime
a[0,3] = 16 + a[1,4]
print(a[0,3])

#change elements value
a[0,3] = 999

#delete elements
a = np.delete(a,1,axis = 0) #delete row 1
print(a)
a = np.delete(a,3) #delete 3rd element
print(a)
a = np.delete(a,[2,3]) #delete multiple elements bu location
print(a)

[[ 2  5  6  5  8  9]
 [ 5  8  9 11 63 59]]
[ 5 11]
63
[ 5  8  9 11 63 59]
79
[[  2   5   6 999   8   9]]
[2 5 6 8 9]
[2 5 9]


# Initalizing value

In [126]:
#Initalizing value

a = np.zeros((2,3), dtype = 'int64') #all zero
print(a)
b = np.ones((2,3), dtype = 'int32') #all one
print(b)
c = np.full((2,3),99) # all 99
print(c)
d = np.full_like(v,4)
print(d)
print(np.random.rand(2,5)) #random decimal numbers

print(np.random.randint(2,7,size = (2,3))) #random integers from 2 to 6

print(np.identity(3)) #identity matrix

# Repeat array values
x = np.array([[1,2,3]])
r1 = np.repeat(x,2,axis=0)
r1

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[99 99 99]
 [99 99 99]]
4
[[0.32765163 0.54639512 0.61716797 0.44825917 0.98657354]
 [0.33976106 0.11116934 0.64190386 0.2556909  0.39524507]]
[[4 5 3]
 [6 6 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1, 2, 3],
       [1, 2, 3]])

# Important

In [140]:
a = np.array([1,2,3])
print(a)
b = a
print(b)
b[0] = 100
print(a)
print(b)
print('\n')
# see the changes
a = np.array([1,2,3])
print(a)
b = a.copy()
print(b)
b[0] = 100
print(a)
print(b)

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]


[1 2 3]
[1 2 3]
[1 2 3]
[100   2   3]


# 1,1,1,1,1
# 1,0,0,0,1
# 1,0,9,0,1
# 1,0,0,0,1
# 1,1,1,1,1
# code to print above format

In [183]:
#code to print above format
a = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
z
a[1:4,1:4] = z
a
#np.linalg.det(a)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# basic Maths

In [184]:
a = np.array([1,5,6,9,8,55,62,2])
a

array([ 1,  5,  6,  9,  8, 55, 62,  2])

In [185]:
a += 2
a

array([ 3,  7,  8, 11, 10, 57, 64,  4])

In [186]:
a - 2

array([ 1,  5,  6,  9,  8, 55, 62,  2])

In [187]:
a = a / 2
a
b = np.array([ 3,  7,  8, 11, 10, 57, 64,  4])
b
z = a + b
print(z)
x = np.array(z,dtype = 'int64')
print(x)

[ 4.5 10.5 12.  16.5 15.  85.5 96.   6. ]
[ 4 10 12 16 15 85 96  6]


In [188]:
#trigonometry
p = np.sin(x)
print(p)

c = np.cos(x)
print(c)

[-0.7568025  -0.54402111 -0.53657292 -0.28790332  0.65028784 -0.17607562
  0.98358775 -0.2794155 ]
[-0.65364362 -0.83907153  0.84385396 -0.95765948 -0.75968791 -0.98437664
 -0.18043045  0.96017029]


# Statistics


In [207]:
# Statistics
b = np.array([[2,5,18],[11,1,9]])
print(b)

[[ 2  5 18]
 [11  1  9]]


In [208]:
np.min(b)

1

In [209]:
np.max(b, axis = 1)

array([18, 11])

In [210]:
np.sum(b)

46

# Re - organizing Arrays

In [223]:
#Reshape
b4 = np.array([[1,2,5,0],[55,86,33,7]])
print(b4)
print()
after = b4.reshape((4,2))
print(after)
print()
after = b4.reshape((2,2,2))
print(after)

[[ 1  2  5  0]
 [55 86 33  7]]

[[ 1  2]
 [ 5  0]
 [55 86]
 [33  7]]

[[[ 1  2]
  [ 5  0]]

 [[55 86]
  [33  7]]]


In [224]:
#Vertically Stacking Vectors
v1 = np.array([5,9,6,8,9])
v2 = np.array([10,7,2,1,3])

np.vstack([v1,v1,v2,v1,v2])

array([[ 5,  9,  6,  8,  9],
       [ 5,  9,  6,  8,  9],
       [10,  7,  2,  1,  3],
       [ 5,  9,  6,  8,  9],
       [10,  7,  2,  1,  3]])

# Load Data from file

In [234]:
files = np.genfromtxt('baba.txt', delimiter=',')
print(files)
print(files.astype('int64'))
files = np.genfromtxt('baba.txt', delimiter=',').astype('int64')
print(files)

[[  5.   9.   6.   8.   9.  11.  22.  99.]
 [  6.   9.   8.   6.  11.  22. 369. 505.]
 [ 88.   9.   7.   5.   2.  13. 999. 101.]]
[[  5   9   6   8   9  11  22  99]
 [  6   9   8   6  11  22 369 505]
 [ 88   9   7   5   2  13 999 101]]
[[  5   9   6   8   9  11  22  99]
 [  6   9   8   6  11  22 369 505]
 [ 88   9   7   5   2  13 999 101]]


# Boolean masking and advance indexing

In [264]:
print(files > 500)
print()
print(~(files > 100) & (files < 700))
print()
print((files > 100) & (files < 700))

[[False False False False False False False False]
 [False False False False False False False  True]
 [False False False False False False  True False]]

[[ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True False False]
 [ True  True  True  True  True  True False False]]

[[False False False False False False False False]
 [False False False False False False  True  True]
 [False False False False False False False  True]]


In [262]:
print(files[files > 500])
print()
print(files[((files > 100) & (files < 700))])
np.all(files > 50 , axis =0)

[505 999]

[369 505 101]


array([False, False, False, False, False, False, False,  True])

In [251]:
v1 = np.array([5,9,6,8,9])
v1 = np.delete(v1,2)
print(v1)
v1[[2,3]]

[5 9 8 9]


array([8, 9])

# Problem

In [276]:
a = np.arange(1,31)
b = a.reshape(6,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [290]:
b[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [283]:
b[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [293]:
b[[0,4,5],2:4]

array([[ 3,  4],
       [23, 24],
       [28, 29]])

In [294]:
b[[0,4,5],2:]

array([[ 3,  4,  5],
       [23, 24, 25],
       [28, 29, 30]])

In [297]:
b[0:,[1,2]]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23],
       [27, 28]])

In [300]:
b[0:3,[1,2]]

6.29 µs ± 392 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Get The loop time of NUMPY

In [301]:
%timeit for i in np.arange(1000000): pass

104 ms ± 4.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [302]:
a = np.arange(1,31)
%timeit b = a.reshape(6,5)
b

589 ns ± 29.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])